Repository Eugeeun/WEB1_1_DoItTogether_FE, pull requests merged in 2024-12, with the labels that each got.

#2 Feature/#1-pages 폴더 재구조
  src/pages/group/GroupCreatePage.tsx
  src/pages/group/GroupInviteReceivePage.tsx
  src/pages/group/GroupSelectPage.tsx
  src/pages/group/GroupSettingPage.tsx
  src/pages/group/PresetSettingPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/housework/HouseWorkStepOnePage.tsx
  src/pages/housework/HouseWorkStepTwoPage.tsx
  src/pages/my/AccountManagePage.tsx
  src/pages/my/LeavePage.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/MyPageEditPage.tsx
  src/pages/register/RegisterPage.tsx
  src/pages/statistics/MonthlyStatisticsPage.tsx
  src/pages/statistics/WeeklyStatisticsPage.tsx
  src/pages/survey/SurveyIntroPage.tsx
  src/pages/survey/SurveyPage.tsx
  src/router.tsx
  src/store/useAddHouseWorkStore.ts
  src/utils/convertStartTime.ts
  src/utils/convertTimeToObject.ts
Labels: 🔨 Refactor

#29 Refactor/#9 - 월간 통계 로직 스타일 분리
  src/components/statistics/monthly/CompletionText/CompletionText.tsx
  src/hooks/useMonthlyStatistics.ts
  src/pages/statistics/MonthlyStatisticsPage.tsx
Labels: 🔨 Refactor

#30 Refactor/#5 - 그룹 세팅 페이지 로직, 스타일 분리
  src/components/common/errorMessage/ErrorMessage.tsx
  src/components/setting/groupSetting/PresetSettingBtn/PresetSettingBtn.tsx
  src/hooks/useGroupSetting.ts
  src/pages/group/GroupSettingPage.tsx
Labels: 🔨 Refactor

#12 Feature/#4-메인(홈) 페이지 로직, 스타일 분리
  src/components/home/NoList/NoList.tsx
  src/components/home/index.ts
  src/hooks/useHomePage.ts
  src/pages/home/HomePage.tsx
Labels: 🔨 Refactor

#32 Feature/#8 - Register 스타일, 로직 분리
  src/hooks/useRegister.ts
  src/pages/register/RegisterPage.tsx
Labels: 🔨 Refactor

#33 Feature/#6-집안일 추가 페이지 로직, 스타일 분리
  src/components/housework/HouseworkForm/HouseworkForm.tsx
  src/components/housework/TaskAssignmentContent/TaskAssignmentContent.tsx
  src/components/housework/index.ts
  src/hooks/useHouseworkStepOne.ts
  src/hooks/useHouseworkStepTwo.ts
  src/pages/housework/HouseWorkStepOnePage.tsx
  src/pages/housework/HouseWorkStepTwoPage.tsx
  src/store/useAddHouseWorkStore.ts
  src/utils/convertStartTime.ts
  src/utils/convertTimeToObject.ts
Labels: 🔨 Refactor

#31 Feature/#7 - 마이페이지 로직, 스타일 분리
  src/components/common/line/Line.tsx
  src/components/my/AccountMenuItem/AccountMenuItem.tsx
  src/components/my/LeaveGuide/LeaveGuide.tsx
  src/hooks/useAccountManage.ts
  src/hooks/useLeave.ts
  src/hooks/useMy.ts
  src/hooks/useMyEdit.ts
  src/pages/my/AccountManagePage.tsx
  src/pages/my/LeavePage.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/MyPageEditPage.tsx
Labels: 🔨 Refactor

#34 Feature/#11-랜딩 페이지 로직, 스타일 분리
  src/components/landing/KakaoLoginButton.tsx
  src/components/landing/ServiceLogo.tsx
  src/components/landing/ServiceTitle.tsx
  src/components/landing/index.ts
  src/hooks/useLanding.ts
  src/pages/LandingPage.tsx
Labels: 🔨 Refactor

#35 Feature/#16-공통 에러처리 적용 및 관련 로직 리팩토링
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/hooks/useGroupSetting.ts
  src/hooks/useHomePage.ts
  src/hooks/useHouseworkStepTwo.ts
  src/hooks/usePresetSetting.ts
  src/hooks/useRegister.ts
  src/hooks/useWeeklyStatistics.ts
  src/pages/group/GroupCreatePage.tsx
  src/pages/group/GroupInviteReceivePage.tsx
  src/pages/group/GroupSelectPage.tsx
  src/services/axiosInstance.ts
  src/services/group/deleteGroupUser.ts
  src/services/group/getGroupUser.ts
  src/services/group/getMyGroup.ts
  src/services/group/postBanUser.ts
  src/services/group/postCreateGroup.ts
  src/services/group/postCreateInviteLink.ts
  src/services/group/postJoinGroup.ts
  src/services/group/putChangeGroupName.ts
  src/services/housework/changeHouseworkStatus.ts
  src/services/housework/deleteHouswork.ts
  src/services/housework/getHouseworkById.ts
  src/services/housework/getHouseworks.ts
  src/services/housework/getWeeklyIncomplete.ts
  src/services/housework/postHousework.ts
  src/services/housework/putHousework.ts
  src/services/noticeManage/postCompliment.ts
  src/services/noticeManage/postPoke.ts
  src/services/onboarding/postPersonalKeyword.ts
  src/services/preset/deleteCategory.ts
  src/services/preset/deletePresetItem.ts
  src/services/preset/getAllCategoryKeywordList.ts
  src/services/preset/getAllCategoryList.ts
  src/services/preset/getAllCategoryName.ts
  src/services/preset/getSingleCategoryList.ts
  src/services/preset/postCreateCategory.ts
  src/services/preset/postCreatePresetItem.ts
  src/services/statistics/getMonthlyMVP.ts
  src/services/statistics/getMonthlyScore.ts
  src/services/statistics/getWeeklyScore.ts
  src/services/statistics/getWeeklyTotalCount.ts
  src/services/user/deleteUser.ts
  src/services/user/getMyInfo.ts
  src/services/user/getMyInitState.ts
  src/services/user/getSpecificUser.ts
  src/services/user/patchMyInfo.ts
  src/services/user/patchMyInitState.ts
Labels: 🔨 Refactor

#36 Feature/#10-설문조사 페이지 로직 분리
  src/components/survey/OnBoarding.stories.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/index.ts
  src/hooks/useSurvey.ts
  src/pages/survey/SurveyPage.tsx
Labels: 🔨 Refactor

#38 Feature/#37-helmet 적용
  package-lock.json
  package.json
  src/components/common/metaTags/MetaTags.tsx
  src/components/statistics/monthly/index.ts
  src/components/statistics/weekly/index.ts
  src/components/survey/index.ts
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/LandingPage.tsx
  src/pages/group/GroupCreatePage.tsx
  src/pages/group/GroupInviteReceivePage.tsx
  src/pages/group/GroupSelectPage.tsx
  src/pages/group/GroupSettingPage.tsx
  src/pages/group/PresetSettingPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/housework/HouseWorkStepOnePage.tsx
  src/pages/housework/HouseWorkStepTwoPage.tsx
  src/pages/my/AccountManagePage.tsx
  src/pages/my/LeavePage.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/MyPageEditPage.tsx
  src/pages/register/RegisterPage.tsx
  src/pages/statistics/MonthlyStatisticsPage.tsx
  src/pages/statistics/WeeklyStatisticsPage.tsx
  src/pages/survey/SurveyIntroPage.tsx
  src/pages/survey/SurveyPage.tsx
Labels: 🔨 Refactor

#41 Feature/#40 - sitemap.xml, robots.txt 추가
  public/robots.txt
  public/sitemap.xml
Labels: 🥰 Accessibility

#42 Feature/#39 - refactor add housework
  src/components/common/bottomNav/BottomNav.tsx
  src/components/housework/HouseworkForm/HouseworkForm.tsx
  src/components/housework/TaskAssignmentContent/TaskAssignmentContent.tsx
  src/components/housework/index.ts
  src/components/housework/steps/Step1.tsx
  src/components/housework/steps/Step2.tsx
  src/hooks/useAddHouseWork.ts
  src/hooks/useHomePage.ts
  src/hooks/useHouseworkStepOne.ts
  src/hooks/useHouseworkStepTwo.ts
  src/pages/housework/AddHouseworkPage.tsx
  src/pages/housework/HouseWorkStepOnePage.tsx
  src/pages/housework/HouseWorkStepTwoPage.tsx
  src/router.tsx
  src/store/useAddHouseWorkStore.ts
  src/utils/convertStartTime.ts
  src/utils/convertTimeToObject.ts
Labels: 🔨 Refactor

#47 Feature/#19-utils 함수 성격별 분류 및 주석 추가
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
  src/hooks/useAddHouseWork.ts
  src/hooks/useWeeklyStatistics.ts
  src/store/useHomePageStore.ts
  src/utils/convertDate.ts
  src/utils/convertTime.ts
  src/utils/convertUtils.ts
  src/utils/dateUtils.ts
  src/utils/getFormattedDate.ts
  src/utils/getWeekText.ts
  src/utils/timeUtils.ts
Labels: 🔨 Refactor

#48 Feature/#21 - 메인 페이지 렌더링 최적화
  index.html
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/hooks/useHomePage.ts
  src/pages/home/HomePage.tsx
Labels: ✨ Feature, 🔨 Refactor

#52 Feature/#49 - 그룹 생성 페이지 로직 분리
  src/hooks/useGroupCreate.ts
  src/pages/group/GroupCreatePage.tsx
Labels: 🔨 Refactor

#53 Feature/#50 - 그룹 초대 페이지 로직 분리
  src/hooks/useGroupInvite.ts
  src/pages/group/GroupInviteReceivePage.tsx
Labels: 🔨 Refactor

#54 Feature/#51 - 그룹 선택 페이지 스타일, 로직 분리
  src/components/groupSelect/GroupList/GroupList.tsx
  src/hooks/useGroupSelect.ts
  src/pages/group/GroupSelectPage.tsx
Labels: 🔨 Refactor

#56 Feature/#55 - 그룹 생성 페이지 성능 최적화
  src/hooks/useGroupCreate.ts
  src/pages/group/GroupCreatePage.tsx
Labels: ✨ Feature, 🔨 Refactor
