Repository Eugeeun/WEB1_1_DoItTogether_FE, pull requests merged in 2025-02, with the labels that each got.

#110 Feature/#109 - 바텀시트 지연로딩 적용
  src/components/housework/steps/Step1.tsx
  src/components/housework/steps/Step2.tsx
Labels: 🔨 Refactor

#112 Feature/#111 - 마이페이지 소셜 로그인 연결 화면에 표시
  src/hooks/useMy.ts
  src/pages/my/AccountManagePage.tsx
  src/types/apis/userApi.ts
Labels: ✨ Feature, 📬 API

#107 Feature/#106 - 전체 화면 기종별 하단 패딩값 추가
  index.html
  src/App.tsx
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/group/create/GroupCreateStep1.tsx
  src/components/group/create/GroupCreateStep2.tsx
  src/components/housework/ActionButton/ActionButton.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
  src/components/survey/steps/Step5.tsx
  src/hooks/useDevice.ts
  src/hooks/useDevicePadding.ts
  src/index.css
  src/pages/ErrorPage.tsx
  src/pages/LandingPage.tsx
  src/pages/group/GroupInviteReceivePage.tsx
  src/pages/group/GroupSelectPage.tsx
  src/pages/group/PresetSettingPage.tsx
  src/pages/housework/AddHouseworkPage.tsx
  src/pages/my/LeavePage.tsx
  src/pages/register/RegisterPage.tsx
  src/pages/survey/SurveyIntroPage.tsx
  src/store/useDeviceStore.ts
Labels: ✨ Feature, 🎨 Html&css

#122 Feature/#119 - 사이트맵 수정
  public/sitemap.xml
Labels: 🥰 Accessibility

#123 Feature/#120 - 푸시알림 실패 토스트
  src/hooks/useHomePage.ts
Labels: ✨ Feature

#124 Feature/#121 - 주간 캘린더 금일 표시
  src/components/home/WeeklyDate/DateItem/DateItem.stories.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
Labels: 🎨 Html&css

#113 Feature/#91 - 로고와 버튼이 겹치는 문제 수정
  src/components/common/button/Button/Button.tsx
  src/components/common/ui/button.tsx
  src/components/landing/LoginButton.tsx
  src/components/landing/LoginButtons.tsx
  src/components/landing/ServiceLogo.tsx
  src/components/landing/ServiceTitle.tsx
  src/components/landing/index.ts
  src/pages/LandingPage.tsx
Labels: 🎨 Html&css

#127 Release v1.1.2
  public/sitemap.xml
  src/components/common/button/Button/Button.tsx
  src/components/common/ui/button.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.stories.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/components/landing/LoginButton.tsx
  src/components/landing/LoginButtons.tsx
  src/components/landing/ServiceLogo.tsx
  src/components/landing/ServiceTitle.tsx
  src/components/landing/index.ts
  src/hooks/useHomePage.ts
  src/pages/LandingPage.tsx
Labels: 🌏 Deploy

#130 Feature/#129 - 개발계, 운영계 분리에 따른 환경 변수 수정
  src/services/axiosInstance.ts
Labels: ⚙ Setting, 📬 API

#132 Feature/#128 - 로그인 환경변수 수정
  src/hooks/useLanding.ts
Labels: 🐞 BugFix

#133 Feature/#128 - fcm 토큰 세션 스토리지 저장 코드 삭제
  src/hooks/useLanding.ts
Labels: ✨ Feature

#135 Feature/#134 - profileimg lazy loading 제거
  src/components/common/profile/ProfileImg.tsx
Labels: 🔨 Refactor

#126 Feature/#125 - 전체 페이지 대상 React.lazy, Suspense 동적 로딩 적용
  src/pages/LandingPage.tsx
  src/pages/group/GroupSettingPage.tsx
  src/pages/group/PresetSettingPage.tsx
  src/pages/home/HomePage.tsx
  src/router.tsx
Labels: ✨ Feature, 🥰 Accessibility

#137 Release v1.2.2
  index.html
  src/components/common/profile/ProfileImg.tsx
  src/hooks/useHomePage.ts
  src/hooks/useLanding.ts
  src/pages/LandingPage.tsx
  src/pages/group/GroupSettingPage.tsx
  src/pages/group/PresetSettingPage.tsx
  src/pages/home/HomePage.tsx
  src/router.tsx
  src/services/axiosInstance.ts
  src/utils/requestForToken.ts
Labels: 🌏 Deploy
