Repository Eugeeun/WEB1_1_DoItTogether_FE, pull requests merged in 2025-03, with the labels that each got.

#140 Feature/#138 - 랜딩 페이지 소셜 로그인 버튼 모션 수정
  src/components/landing/ServiceLogo.tsx
  src/pages/LandingPage.tsx
Labels: 🎨 Html&css

#141 ✨ Feat: 집안일 추가 로직에 status 추가
  src/hooks/useAddHouseWork.ts
  src/services/housework/postHousework.ts
  src/services/housework/putHousework.ts
  src/store/useAddHouseWorkStore.ts
  src/types/apis/houseworkApi.ts
Labels: ✨ Feature

#142 ✨ Feat: AI 할당 기능 추가
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.stories.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.stories.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/components/housework/steps/Step1.tsx
  src/components/housework/steps/Step2.tsx
  src/hooks/useAddHouseWork.ts
  src/pages/housework/AddHouseworkPage.tsx
  src/services/housework/getTargetUserId.ts
  src/services/housework/postAssignHouseworkAi.ts
  src/types/apis/houseworkApi.ts
Labels: ✨ Feature

#145 Fix/#144 - 프리셋페이지 사용자정의 입력창 버튼 수정
  src/hooks/usePresetSetting.ts
Labels: 🐞 BugFix

#146 Release v1.2.4
  src/hooks/usePresetSetting.ts
Labels: 🌏 Deploy

#156 Release v1.2.5
  src/App.tsx
  src/components/LoadingRedirect.tsx
  src/utils/browserDetect.ts
  src/utils/fcm.ts
Labels: 🌏 Deploy

#158 Feature/#157 - 설정 버튼 그룹 목록 페이지에 추가 및 알림 toggle 추가
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/components/my/FcmToggle/FcmToggle.tsx
  src/hooks/useAccountManage.ts
  src/hooks/useLanding.ts
  src/hooks/useLeave.ts
  src/hooks/useNotification.ts
  src/pages/group/GroupSelectPage.tsx
  src/pages/my/AccountManagePage.tsx
  src/router.tsx
  src/services/fcm/deleteFcmToken.ts
  src/types/apis/fcmApi.ts
Labels: ✨ Feature
