Repository Eugeeun/WEB1_1_DoItTogether_FE, pull requests merged in 2025-01, with the labels that each got.

#60 Feature/#59 - 그룹 선택 페이지 제목 줄 간격 업데이트
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx
Labels: 🎨 Html&css

#62 Feature/#61 - 집안일 추가 라우팅 수정
  src/components/common/bottomNav/BottomNav.tsx
  src/hooks/useHomePage.ts
Labels: 🐞 BugFix

#63 Feature/#45 - 그룹 설정 페이지 성능 최적화
  src/components/setting/groupSetting/MemberItems/MemberItems.tsx
  src/hooks/useGroupSetting.ts
  src/pages/group/GroupSettingPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#65 Fix/#64 - fix add housework page
  src/components/housework/DueDateSheet/DueDateSheet.stories.ts
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/housework/HouseworkForm/HouseworkForm.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeControl/TimePicker/TimePicker.tsx
  src/components/housework/steps/Step1.tsx
  src/components/housework/steps/Step2.tsx
  src/hooks/useAddHouseWork.ts
  src/pages/housework/AddHouseworkPage.tsx
  src/store/useAddHouseWorkStore.ts
Labels: 🐞 BugFix

#68 Feature/#66 - 주간 통계 페이지 성능 최적화 & 리팩토링
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
  src/hooks/useWeeklyStatistics.ts
  src/pages/statistics/WeeklyStatisticsPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#70 Feature/#67 - 월간 통계 최적화
  src/components/statistics/monthly/CompletionText/CompletionText.tsx
  src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/hooks/useMonthlyStatistics.ts
  src/pages/statistics/MonthlyStatisticsPage.tsx
Labels: 🔨 Refactor

#71 Feature/#25 - 회원가입 최적화
  src/components/common/errorMessage/ErrorMessage.tsx
  src/components/common/input/InputWithLabel.tsx
  src/components/common/metaTags/MetaTags.tsx
  src/components/common/profile/ProfileImg.tsx
  src/hooks/useRegister.ts
Labels: 🔨 Refactor

#72 Feature/#24 - 마이페이지 최적화
  src/components/common/alert/AlertDialogProps.tsx
  src/components/common/header/Header.tsx
  src/components/my/AccountInfo/AccountInfo.tsx
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/components/my/LeaveGuide/LeaveGuide.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/hooks/useMy.ts
  src/hooks/useMyEdit.ts
Labels: 🔨 Refactor

#69 Feature/#23 - imporve add housework
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/BottomSheetTitle/BottomSheetTitle.tsx
  src/components/common/bottomSheet/CloseBtn/CloseBtn.tsx
  src/components/common/button/Button/Button.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/common/tab/PresetTab/PresetTabItem.tsx
  src/components/housework/ActionButton/ActionButton.tsx
  src/components/housework/HeaderWithTitle/HeaderWithTitle.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/housework/HouseworkForm/HouseworkForm.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItem.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/components/housework/TaskAssignmentContent/TaskAssignmentContent.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeLabel/TimeLabel.tsx
  src/components/housework/steps/Step1.tsx
  src/constants/addHousework.ts
  src/hooks/useAddHouseWork.ts
  src/hooks/useHomePage.ts
  src/pages/housework/AddHouseworkPage.tsx
  src/store/useAddHouseWorkStore.ts
Labels: 🔨 Refactor

#74 Feature/#28 - 랜딩 페이지 성능 최적화
  index.html
  package-lock.json
  package.json
  src/components/landing/ServiceLogo.tsx
  src/pages/LandingPage.tsx
  tailwind.config.js
  vite.config.ts
Labels: ⚙ Setting, 🔨 Refactor

#75 Feature/#46 - 프리셋 설정 페이지 성능 최적화
  src/components/common/preset/PresetItem.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/common/tab/PresetTab/PresetTabItem.tsx
  src/components/common/tab/Tab/Tab.tsx
  src/components/setting/presetSetting/PresetAddInput.stories.ts
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.tsx
  src/constants/index.ts
  src/hooks/usePresetSetting.ts
  src/pages/group/PresetSettingPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#79 Feature/#77-주간통계 페이지 화면 수정
  src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatActions.tsx
  src/pages/statistics/WeeklyStatisticsPage.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#82 Feature/#81 add google search console
  index.html
  public/google3b4de01103e0b871.html
Labels: 🥰 Accessibility

#84 Feature/#83 - refactor select date
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/store/useAddHouseWorkStore.ts
Labels: 🔨 Refactor

#87 Release 1.1.1
  .gitignore
  index.html
  package-lock.json
  package.json
  public/google3b4de01103e0b871.html
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatActions.tsx
  src/pages/statistics/WeeklyStatisticsPage.tsx
  src/store/useAddHouseWorkStore.ts
  vite.config.ts
Labels: 🌏 Deploy

#89 Release v1.1.2
  vite.config.ts
Labels: 🌏 Deploy

#93 Feature/#92 - 네이버 서치 콘솔 등록
  index.html
Labels: 🥰 Accessibility

#95 Release v1.1.2
  index.html
Labels: 🌏 Deploy, 🥰 Accessibility

#94 Feature/#91 - 소셜 로그인(구글, 네이버) 추가
  index.html
  src/components/common/button/Button/Button.tsx
  src/components/common/icon/GoogleIcon.tsx
  src/components/common/icon/KakaoIcon.tsx
  src/components/common/icon/NaverIcon.tsx
  src/components/common/icon/index.ts
  src/components/common/ui/button.tsx
  src/components/landing/KakaoLoginButton.tsx
  src/components/landing/LoginButton.tsx
  src/components/landing/index.ts
  src/hooks/useLanding.ts
  src/pages/LandingPage.tsx
  tailwind.config.js
Labels: ✨ Feature, 📬 API

#98 Feature/#93 - 이용약관&개인정보 처리방침 버튼 추가
  src/components/my/AccountMenuItem/AccountMenuItem.tsx
  src/hooks/useAccountManage.ts
  src/pages/my/AccountManagePage.tsx
Labels: ✨ Feature, 🎨 Html&css

#103 Feature/#100 add firebase config
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/utils/requestForToken.ts
Labels: ✨ Feature

#105 Feature/#104 - 로고 아이콘 png파일 변경
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
Labels: 🎨 Html&css

#102 Feature/#99 - refactor use survey
  .vscode/typescriptreact.code-snippets
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
  src/components/survey/steps/Step5.tsx
  src/hooks/survey/useLoadingState.ts
  src/hooks/survey/useSurveyState.ts
  src/hooks/survey/useUserName.ts
  src/hooks/useFunnel.tsx
  src/hooks/useSurvey.ts
  src/pages/survey/SurveyPage.tsx
  src/types/surveySteps.ts
Labels: 🔨 Refactor
